default:
  api_login_id: 6w68gNZT
  api_transaction_key: 839rnL9BB55Kfb8J
  merchant_hash_value: Simon

# Sign-up
# http://developer.authorize.net/hello_world/
# Transaction Gateway
# https://sandbox.authorize.net/
development:
  api_login_id: 6w68gNZT
  api_transaction_key: 839rnL9BB55Kfb8J
  merchant_hash_value: Simon
test:
production:
